CREATE TABLE MANUFACTURERS_AUD (
                          EVENT_ID INT(11) NOT NULL AUTO_INCREMENT,
                          EVENT_DATE DATETIME NOT NULL,
                          EVENT_TYPE VARCHAR(10) DEFAULT NULL,
                          MANUFACTURER_ID INT(11) NOT NULL,
                          OLD_NAME VARCHAR(255),
                          NEW_NAME VARCHAR(255),
                          PRIMARY KEY (EVENT_ID)
);

DELIMITER $$
CREATE TRIGGER MANUFACTURERS_INSERT AFTER INSERT ON manufacturers
    FOR EACH ROW
BEGIN
    INSERT INTO MANUFACTURERS_AUD (EVENT_DATE, EVENT_TYPE, MANUFACTURER_ID, NEW_NAME)
        VALUE(CURTIME(), 'INSERT', NEW.manufacturer_id, NEW.name);
END $$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER MANUFACTURERS_DELETE AFTER DELETE ON manufacturers
    FOR EACH ROW
BEGIN
    INSERT INTO MANUFACTURERS_AUD (EVENT_DATE, EVENT_TYPE, MANUFACTURER_ID)
        VALUE(CURTIME(), 'DELETE', OLD.manufacturer_id);
END $$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER MANUFACTURERS_UPDATE AFTER UPDATE ON manufacturers
    FOR EACH ROW
BEGIN
    INSERT INTO MANUFACTURERS_AUD (EVENT_DATE, EVENT_TYPE, MANUFACTURER_ID, OLD_NAME, NEW_NAME)
        VALUE(CURTIME(), 'UPDATE', OLD.manufacturer_id, OLD.name, NEW.name);
END $$
DELIMITER ;