CREATE TABLE MODELS_AUD (
                             EVENT_ID INT(11) NOT NULL AUTO_INCREMENT,
                             EVENT_DATE DATETIME NOT NULL,
                             EVENT_TYPE VARCHAR(10) DEFAULT NULL,
                             MODEL_ID INT(11) NOT NULL,
                             OLD_MANUFACTURER_ID INT(11),
                             NEW_MANUFACTURER_ID INT(11),
                             OLD_NAME VARCHAR(255),
                             NEW_NAME VARCHAR(255),
                             OLD_ENGINE_SIZE DOUBLE(9,2),
                             NEW_ENGINE_SIZE DOUBLE(9,2),
                             OLD_BODY_TYPE ENUM('SEDAN', 'COUPE', 'ESTATE', 'HATCHBACK', 'SUV'),
                             NEW_BODY_TYPE ENUM('SEDAN', 'COUPE', 'ESTATE', 'HATCHBACK', 'SUV'),
                             OLD_PRODUCTION_YEAR INT(11),
                             NEW_PRODUCTION_YEAR INT(11),
                             OLD_COLOR VARCHAR(255),
                             NEW_COLOR VARCHAR(255),
                             OLD_SEATS_QUANTITY INT(11),
                             NEW_SEATS_QUANTITY INT(11),
                             OLD_DOOR_QUANTITY INT(11),
                             NEW_DOOR_QUANTITY INT(11),
                             OLD_FUEL_TYPE ENUM('DIESEL', 'PETROL', 'LPG', 'ELECTRIC'),
                             NEW_FUEL_TYPE ENUM('DIESEL', 'PETROL', 'LPG', 'ELECTRIC'),
                             OLD_TRANSMISSION_TYPE ENUM('AUTOMATIC', 'MANUAL'),
                             NEW_TRANSMISSION_TYPE ENUM('AUTOMATIC', 'MANUAL'),
                             PRIMARY KEY (EVENT_ID)
);

DELIMITER $$
CREATE TRIGGER MODELS_INSERT AFTER INSERT ON models
    FOR EACH ROW
BEGIN
    INSERT INTO MODELS_AUD (EVENT_DATE, EVENT_TYPE, MODEL_ID, NEW_MANUFACTURER_ID, NEW_NAME, NEW_ENGINE_SIZE, NEW_BODY_TYPE, NEW_PRODUCTION_YEAR,
                             NEW_COLOR, NEW_SEATS_QUANTITY, NEW_DOOR_QUANTITY, NEW_FUEL_TYPE, NEW_TRANSMISSION_TYPE)
        VALUE(CURTIME(), 'INSERT', NEW.MODEL_ID, NEW.MANUFACTURER, NEW.NAME, NEW.ENGINE_SIZE, NEW.BODY_TYPE, NEW.PRODUCTION_YEAR,
              NEW.COLOR, NEW.SEATS_QUANTITY, NEW.DOOR_QUANTITY, NEW.FUEL_TYPE, NEW.TRANSMISSION_TYPE);
END $$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER MODELS_DELETE AFTER DELETE ON models
    FOR EACH ROW
BEGIN
    INSERT INTO MODELS_AUD (EVENT_DATE, EVENT_TYPE, MODEL_ID)
        VALUE(CURTIME(), 'DELETE', OLD.model_id);
END $$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER MODELS_UPDATE AFTER UPDATE ON models
    FOR EACH ROW
BEGIN
    INSERT INTO MODELS_AUD (EVENT_DATE, EVENT_TYPE, MODEL_ID, NEW_MANUFACTURER_ID, OLD_MANUFACTURER_ID, NEW_NAME, OLD_NAME,
                            NEW_ENGINE_SIZE, OLD_ENGINE_SIZE, NEW_BODY_TYPE, OLD_BODY_TYPE, NEW_PRODUCTION_YEAR, OLD_PRODUCTION_YEAR,
                            NEW_COLOR, OLD_COLOR, NEW_SEATS_QUANTITY, OLD_SEATS_QUANTITY, NEW_DOOR_QUANTITY, OLD_DOOR_QUANTITY,
                            NEW_FUEL_TYPE, OLD_FUEL_TYPE, NEW_TRANSMISSION_TYPE, OLD_TRANSMISSION_TYPE)
        VALUE(CURTIME(), 'UPDATE', OLD.MODEL_ID, NEW.MANUFACTURER, OLD.MANUFACTURER, NEW.NAME, OLD.NAME,
              NEW.ENGINE_SIZE, OLD.ENGINE_SIZE, NEW.BODY_TYPE, OLD.BODY_TYPE, NEW.PRODUCTION_YEAR, OLD.PRODUCTION_YEAR,
              NEW.COLOR, OLD.COLOR, NEW.SEATS_QUANTITY, OLD.SEATS_QUANTITY, NEW.DOOR_QUANTITY, OLD.DOOR_QUANTITY,
              NEW.FUEL_TYPE, OLD.FUEL_TYPE, NEW.TRANSMISSION_TYPE, OLD.TRANSMISSION_TYPE);
END $$
DELIMITER ;